### ISSUE TITLE
disableAck not working?

### ISSUE THREAD

**Issue by jumpjack** [Pixelbo/Pelco_And_Arduino#3]
https://github.com/Pixelbo/Pelco_And_Arduino/blob/5c4c4367be48858c0e1fbb1efee25626cd4064a0/src/PelcoBus.cpp#L104

Is disableAck  working? I always get a "missing ack error", whatever value I specify, true or false.

----

Shouldn't this return "true" if disableAck is true? 

https://github.com/Pixelbo/Pelco_And_Arduino/blob/5c4c4367be48858c0e1fbb1efee25626cd4064a0/src/PelcoCam.cpp#L49

**Comment by Pixelbo** [comment]
disableAck is working, 
https://github.com/Pixelbo/Pelco_And_Arduino/blob/5c4c4367be48858c0e1fbb1efee25626cd4064a0/src/PelcoBus.cpp#L167

This if statement control a big chunk of code which control if the ACK alogrithm should run or not. Could you show your initialization code and/or the serial output of the arduino? 
***
As for https://github.com/Pixelbo/Pelco_And_Arduino/blob/5c4c4367be48858c0e1fbb1efee25626cd4064a0/src/PelcoCam.cpp#L49 yeah it should be true, but with "disableAck" set to true, you can't verify if the camera is working.

**Comment by jumpjack** [comment]
Have you got a working example? I always receive an error message about missing camera, whatever I do. How can I send "blind" commands?

**Comment by Pixelbo** [comment]
The exemple old_model.ino is a clear exemple of a PelcoCam with ACK disabled.
