### ISSUE TITLE
Bug in PelcoBus::send_raw

### ISSUE THREAD

**Issue by jumpjack** [Pixelbo/Pelco_And_Arduino#4]
https://github.com/Pixelbo/Pelco_And_Arduino/blob/5c4c4367be48858c0e1fbb1efee25626cd4064a0/src/PelcoBus.cpp#L104

**messFromCamera** shold be instead **raw_command**; indeed, the command is properly sent, but wrong string is displayed in serial monitor:

```
Cam 1: Wrong checksum, updating to right checksum
Cam 1: sending message 00 00 00 00 00 00 00 
```

**Comment by Pixelbo** [comment]
Indeed, thank you for noticing! It will be fixed in the next release.
