### ISSUE TITLE
Error in ACK message

### ISSUE THREAD

**Issue by jumpjack** [Pixelbo/Pelco_And_Arduino#5]
https://github.com/Pixelbo/Pelco_And_Arduino/blob/5c4c4367be48858c0e1fbb1efee25626cd4064a0/src/PelcoBus.cpp#L206C52-L206C66

I think **messFromcamera** should be **ACKmessFromCamera**

**Comment by Pixelbo** [comment]
Indeed, thanks a lot! I think I did a lot of copy-paste back then.

It will be fixed in the next release.

**Comment by jumpjack** [comment]
Do you think you could add an info message which shows in serial console the library version upon loading the library?

**Comment by Pixelbo** [comment]
Version will be displayed when PelcoBus is initialized. (if the logs are turned on)

**Comment by jumpjack** [comment]
Great job! :-)

In case you are interested, you can find your library applied in this simulated project: https://wokwi.com/projects/392057678139446273

Now that it works in theory, I am awaiting for parts to arrive, to actually build it. :-)

I had to create from scracth the MAX485 simulator with pelco-d processing, because none was available.
