### ISSUE TITLE
Undefined "baud"

### ISSUE THREAD

**Issue by jumpjack** [Pixelbo/Pelco_And_Arduino#7]
Arduino compiler complains about possibly undefined value for "baud"; I think it depends on lack of "default" branch in  switch/case above: after adding "default: baud = 2400;" the warning disappeared.

https://github.com/Pixelbo/Pelco_And_Arduino/blob/baf1b56ab50e260e28eddf4d161633485579e9c7/src/PelcoBus.cpp#L89

**Comment by Pixelbo** [comment]
fixed
